name: vue upgrade

on:
  push:
    branches:
      - develop

jobs:
  vue_upgrade:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - run: npm ci
      - uses: nwtgck/actions-vue-upgrade@develop
